title: Jatin K Malik
#url: "https://jatinkrmalik.github.io"
#baseurl: "/researcher"
site.favicon_location: "favicon.ico"
markdown: kramdown

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass
